#数据库设置
spring:
  application:
    name: demo
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    serialization:
      write-dates-as-timestamps: true
  #数据库设置
  ##数据库连接信息
  datasource:
    # 使用阿里的Druid连接池
    # type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    # 填写你数据库的url、登录名、密码和数据库名


server:
  port: 8084



## 其他配置文件
swagger:
  ip: 127.0.0.1