
#数据库设置
spring:
  ##数据库连接信息
  datasource:
    # 填写你数据库的url、登录名、密码和数据库名
    url: jdbc:mysql://127.0.0.1:3306/MyTest?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&autoReconnect=true&autoReconnectForPools=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: xxxxxx
